package com.trio.stride.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFD10A46)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA50034)
val onPrimaryContainerLight = Color(0xFFFFE4E5)
val secondaryLight = Color(0xFFFF7989)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA63648)
val onSecondaryContainerLight = Color(0xFF740D26)
val tertiaryLight = Color(0xFFB14A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8A3800)
val onTertiaryContainerLight = Color(0xFFFFE5DA)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF281718)
val surfaceLight = Color(0xFFF0F0F0)
val onSurfaceLight = Color(0xFF281718)
val surfaceVariantLight = Color(0xFFFFDADB)
val onSurfaceVariantLight = Color(0xFF5C3F41)
val outlineLight = Color(0xFF906F71)
val outlineVariantLight = Color(0xFFE4BDBF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3F2B2D)
val inverseOnSurfaceLight = Color(0xFFFFECED)
val inversePrimaryLight = Color(0xFFFFB2B8)
val surfaceDimLight = Color(0xFFF1D3D4)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F0)
val surfaceContainerLight = Color(0xFFFFE9E9)
val surfaceContainerHighLight = Color(0xFFFFE1E2)
val surfaceContainerHighestLight = Color(0xFFFADBDC)

val primaryDark = Color(0xFFFFB2B8)
val onPrimaryDark = Color(0xFF67001D)
val primaryContainerDark = Color(0xFFD10A46)
val onPrimaryContainerDark = Color(0xFFFFE4E5)
val secondaryDark = Color(0xFFFFB2B8)
val onSecondaryDark = Color(0xFF67011E)
val secondaryContainerDark = Color(0xFF861D32)
val onSecondaryContainerDark = Color(0xFFFF98A2)
val tertiaryDark = Color(0xFFFFB692)
val onTertiaryDark = Color(0xFF562000)
val tertiaryContainerDark = Color(0xFFB14A00)
val onTertiaryContainerDark = Color(0xFFFFE5DA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1F0F10)
val onBackgroundDark = Color(0xFFFADBDC)
val surfaceDark = Color(0xFF1F0F10)
val onSurfaceDark = Color(0xFFFADBDC)
val surfaceVariantDark = Color(0xFF5C3F41)
val onSurfaceVariantDark = Color(0xFFE4BDBF)
val outlineDark = Color(0xFFAB888A)
val outlineVariantDark = Color(0xFF5C3F41)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFADBDC)
val inverseOnSurfaceDark = Color(0xFF3F2B2D)
val inversePrimaryDark = Color(0xFFBE003D)
val surfaceDimDark = Color(0xFF1F0F10)
val surfaceBrightDark = Color(0xFF483435)
val surfaceContainerLowestDark = Color(0xFF190A0B)
val surfaceContainerLowDark = Color(0xFF281718)
val surfaceContainerDark = Color(0xFF2C1B1C)
val surfaceContainerHighDark = Color(0xFF382527)
val surfaceContainerHighestDark = Color(0xFF433031)






